[package]
name = "agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agent-sql = { path = "../agent-sql" }
models = { git = "https://github.com/estuary/flow", branch = "master" }
tables = { git = "https://github.com/estuary/flow", branch = "master", features = ["persist"] }

anyhow = "*"
async-trait = "*"
base64 = "*"
bytes = "*"
chrono = { version = "0.4" }
clap = { version = "*", features = ["derive", "env"] }
futures = "*"
itertools = "*"
reqwest = { version = "*", default_features = false, features = ["json", "native-tls"] }
rusqlite = "*"
schemars = "*"
scopeguard = "*"
serde = { version = "*", features = ["derive"] }
serde_json = { version = "*" }
sqlx = { version = "*", features = [ "chrono", "json", "macros", "postgres", "runtime-tokio-native-tls", "uuid" ] }
tempfile = "*"
thiserror = "*"
tokio = { version = "1", features = ["full"] }
tokio-util = "*"
tracing = "*"
tracing-subscriber = {version = "*", features = ["json", "env-filter", "fmt", "time"]}
url = "*"
validator = "*"

[dev-dependencies]
insta = { version = "*", features = ["redactions"] }
tokio = { version = "1", features = ["rt", "net", "macros"] }
