import:
  - derivations.flow.yaml

materializations:
  estuary/ops/task-stats/to-postgres:
    shards:
      logLevel: info
      # Keep transactions open a little longer, because we have lots of stats documents to process,
      # and a relatively small number of distinct keys. So we're likely to do lots of reductions if
      # we give it a little time.
      minTxnDuration: 30s
      maxTxnDuration: 1m
    endpoint:
      flowSink:
        image: ghcr.io/estuary/materialize-postgres:dev
        config: stats-materialization-endpoint.sops.yaml

    bindings:
      - source: estuary/ops/task-stats/by-minute
        resource:
          table: task_stats_by_minute
        fields:
          recommended: false
          include:
            kind: {}
            name: {}
            key_begin: {}
            rclock_begin: {}
            ts: {}
            flow_document: {}
      - source: estuary/ops/task-stats/by-hour
        resource:
          table: task_stats_by_hour
        fields:
          recommended: false
          include:
            kind: {}
            name: {}
            key_begin: {}
            rclock_begin: {}
            ts: {}
            flow_document: {}
      - source: estuary/ops/task-stats/by-day
        resource:
          table: task_stats_by_day
        fields:
          recommended: false
          include:
            kind: {}
            name: {}
            key_begin: {}
            rclock_begin: {}
            ts: {}
            flow_document: {}
